### ISSUE TITLE
Graphical User Interface

### ISSUE THREAD

**Issue by n-laaser** [n-laaser/SwEwProject-Laaser.Treunert#2]
Programmiere ein Programm welches ein GUI erstellt das der Bedienung des Nullstellengenerators dient. 
Ein Feld ist für die Auswahl des Grad des Polynoms (Usereingabe: 1-5) und eine Checkbox um auch rationale Nullstellen einzubeziehen.
Dann soll man einen Knopf drücken wodurch eine Funktion welche der Auswahl entspricht, generiert und angezeigt wird. 
Zuletzt sollen 2 Knöpfe verfügbar sein. Einmal "Funktions-Plot zeigen" welcher die Funktion mit "ScottPlot" in einem seperaten Fenster darstellt und "Lösung zeigen", wodurch die Nullstellen angezeigt werden und der Plot ebenfalls gezeigt wird.

**Comment by Leno27** [comment]
Das GUI erfüllt nun alle Anforderungen die dafür vorgesehen sind. 
Zudem wurde es mit Polynomial verknüpft und stellt die dadurch gegebene Funktion und Graph korrekt dar.
