### ISSUE TITLE
Softwareentwurf aktualisieren

### ISSUE THREAD

**Issue by Leno27** [n-laaser/SwEwProject-Laaser.Treunert#7]
Wenn Polynomial und das GUI zufriedenstellen sind, werden alle neu hinzugekommenen Elemente dem UML-Diagramm beigefügt.

**Comment by n-laaser** [comment]
![Klassen](https://www.plantuml.com/plantuml/png/XLFDRjiy4BppAGIVvC-V10H5UyWfjWi30Nm8ug275eMn8jSEOP9ha9GZDyYxbzQ_8W6zYREpizpXwC5vi3xNYd45paKRilhkdIK2ZnOnke-ayIonu2KPK7_GaWjWHgHOqfm4vPd2NxzPegLpqXoRmj9Qk6wby_6S9MTILqCwm4_LbmGLSBPO6lU6LfgVTTU5f60BJZgZ5HLt-nqgv1x5en5Oh5_1755qj5VafvAsldsX-4p8Sk_9XBAI_DIYvPhxBK57t97ARrkkoeQAtzIUiRHfK2ehQNgsyW8U8m4UqfGLUxWjtNVbEeO-QhUtaA4ARl-GJePAw-mB5ZuSdBV1pPPTZH_JFtflvvuK-Gd5Ody1bUFmkQvZi1KhxSoeY2R4Qgi_pr_NJpRHyUXHk_56jpt3Z7ywaAo0dpWfiW7RNLrGIxzRU0krT7s3quqblRJ7B9u7yLgzozdxT8H7CJVY0DoJRGsP2ZadF1o6q24tlBfgT-V54Qj8nuFH_qVLp7bVOC51yNMf6vUiOLN32JVjYBYwmBmtQXCNNGTRlD0kFwFTSIlFFkw8uxY6ZU-ZPp22TELS-MD4b2Gzzshmlm0sJzo3PjzcLOxxs9TPdTOExEBPOMtA-hrVPqqks0CQaMlr5m00)

**Comment by n-laaser** [comment]
Aktualisierter Softwareentwurf, nicht vollkommen finalisiert

**Comment by n-laaser** [comment]
![Klassen](https://www.plantuml.com/plantuml/png/XLB1Yjim4BthAqnEJbq5bj9BJvku11PoMEgbXvOIP7dY5P4rGP9txIxxxvKjnv7NXjwaDqzlHc_UlR5CsxgIX4jcJBH7NTsz4Lf0gG6YRv5Gbb3Dh435v5_GQ1oO8qf2hxS2wrp2xp-4Nb2s2Yk7FVgJO99KmXYXoYjxgpLh3y9OqXnPTmuLsZb4AIN9LfbNq4Bz6aHUK1GauLZbkCFcxfY116wXU505DEapKoKKDzepy7DFIxiJ51y9UMqjAbUMWfz7jBVYU41s8sOewyw9NV_0yw-r7z1REIdrbVV1sWFBGJfhVmeZSWcZZK_GM7SnLZkNHhRNcTFVWqMPHubsGR4vlZ1PmtGtxHmSnNfVScoY1R71iu_zqy7xXHSF5Yep_r7tJzVZlmxG7UDdZXArmxBMEBNDTyrUNMsJTl1chx7QwZAFrqxSgmU1UrlEwopJgZWnRb6FXYmbcYESJbFeL2lkHxtDd9JWinbFMd-EVCzrA91m9ddQwyOzQrgjs1dsOulO3x0EMktZvlQ294-OrHVG6TVYOkE0wApf8nmXfO4z0_Y9qd670RJwkl913R4lgo6E0JZcBy1yZ6Pwm-B9FQYYhkG_)
