### ISSUE TITLE
Wiki aktualisieren 

### ISSUE THREAD

**Issue by Leno27** [n-laaser/SwEwProject-Laaser.Treunert#8]
Projekt erneut kurz erklären und eventuell Funktionsweise des Programms erklären (Tutorial). Zudem erklären was alles benötigt wird, um das Projekt auf dem eigenen Gerät auszuführen.

**Comment by n-laaser** [comment]
Ich mach einen Eintrag zu den Problemen welche beim Programmieren auftraten.

**Comment by Leno27** [comment]
Dadurch dass der Release jetzt auch fertig ist, konnte ich den letzten Teil des Wikis beenden (Herunterladen des Projekts)
